### ISSUE TITLE
fix: Ghostty v1.3.1 read_clipboard_cb return type mismatch breaks build

### ISSUE THREAD

**Issue by rube-de** [salexandr0s/pnevma#43]
## Context

After bumping Ghostty to v1.3.1 (commit `4459819`), the native macOS app fails to compile. The Ghostty v1.3.1 C API changed the `ghostty_runtime_read_clipboard_cb` typedef to return `bool` instead of `void`. The Swift closure in `TerminalSurface.swift` was not updated to match, causing a compiler error that blocks any debug or release build.

**Severity:** P1/High
**Reproducibility:** Always — deterministic build failure on `just build` after pulling the Ghostty bump
**Regression:** Yes (since commit `4459819 chore(ghostty): bump Ghostty to v1.3.1 and Zig to 0.15.2`)

## Reproduction Steps

1. Pull the latest `main` branch containing the Ghostty v1.3.1 bump
2. Run `just ghostty-build` to rebuild the xcframework (requires Zig 0.15.2)
3. Run `just build` or `just xcode-build`
4. Observe: Swift compilation fails in `TerminalSurface.swift`

**Expected:** Native app builds successfully
**Actual:** Build fails with:
```
TerminalSurface.swift:493: error: missing return in closure expected to return 'Bool'
```

## Error Output

```
/Users/.../native/Pnevma/Terminal/TerminalSurface.swift:493:13: error: missing return in closure expected to return 'Bool'
```

Note: with stale DerivedData, Xcode may instead report misleading errors about `ghostty_clipboard_content_s` not found or argument count mismatches. A clean DerivedData reveals the true error.

## Root Cause Analysis

**Suspected cause:** Ghostty v1.3.1 changed the C typedef:
```c
// Before (v1.1.x):
typedef void (*ghostty_runtime_read_clipboard_cb)(void*, ghostty_clipboard_e, void*);

// After (v1.3.1):
typedef bool (*ghostty_runtime_read_clipboard_cb)(void*, ghostty_clipboard_e, void*);
```

The `read_clipboard_cb` closure in `TerminalSurface.makeRuntimeConfig()` had no return statement. Swift infers `Void` return, which doesn't match the new `Bool` return requirement.

**Affected component:** `native/Pnevma/Terminal/TerminalSurface.swift` — the `makeRuntimeConfig()` method that builds the Ghostty runtime callback struct.

## Acceptance Criteria

- [ ] VERIFY: `just build` succeeds after a clean `just ghostty-build` with Ghostty v1.3.1
- [ ] VERIFY: `read_clipboard_cb` closure returns `true` (signals async clipboard handling)
- [ ] VERIFY: Clipboard paste from host into Ghostty terminal still works at runtime
- [ ] VERIFY: No existing tests broken by the fix (`just test`)

### Files to Modify
- `native/Pnevma/Terminal/TerminalSurface.swift` — add `return true` to `read_clipboard_cb` closure

### Approach
1. In `TerminalSurface.makeRuntimeConfig()`, locate the `read_clipboard_cb` closure (line ~483)
2. Add `return true` before the closing brace — this signals to Ghostty that the runtime will provide clipboard data asynchronously via `completeClipboardRead`
3. Verify build: `just build`
4. Verify runtime: paste text into an active terminal session

### Constraints
- The return value semantics come from Ghostty's API: `true` = "I handled this read request and will provide data asynchronously", `false` = "I can't provide clipboard data"
- Must not change `confirm_read_clipboard_cb` or `write_clipboard_cb` — their signatures are unchanged in v1.3.1

### In Scope
- Fix the `read_clipboard_cb` return type mismatch

### Out of Scope
- Refactoring other Ghostty callbacks
- Adding the local vsync display-link fallback patch (previously in vendor checkout, not upstreamed)
- Updating other Ghostty API usages beyond what's broken
